# Generated by Django 3.0.8 on 2020-08-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20000)),
                ('source', models.CharField(max_length=20000)),
                ('author', models.CharField(max_length=20000)),
                ('description', models.CharField(max_length=20000)),
                ('content', models.CharField(max_length=20000)),
            ],
        ),
    ]
