# Generated by Django 3.0.8 on 2020-08-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0002_hotnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotnews',
            name='author',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='content',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='description',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='source',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='title',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
