# Generated by Django 3.0.8 on 2020-08-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0003_auto_20200801_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotnews',
            name='content',
            field=models.CharField(max_length=200000, null=True),
        ),
    ]
