# Generated by Django 3.0.8 on 2020-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0004_auto_20200801_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20000, null=True)),
                ('source', models.CharField(max_length=20000, null=True)),
                ('author', models.CharField(max_length=20000, null=True)),
                ('description', models.CharField(max_length=20000, null=True)),
                ('content', models.CharField(max_length=200000, null=True)),
            ],
        ),
    ]
