# Generated by Django 3.0.8 on 2020-08-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0005_searchnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchnews',
            name='urls',
            field=models.CharField(max_length=200000, null=True),
        ),
    ]
