# Generated by Django 3.0.8 on 2020-08-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0008_idnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idnews',
            name='idtitle',
            field=models.IntegerField(blank=True),
        ),
    ]
