# Generated by Django 3.0.8 on 2020-08-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0009_auto_20200806_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20000, null=True)),
                ('keyword', models.CharField(max_length=20000, null=True)),
            ],
        ),
    ]
