# Generated by Django 3.0.8 on 2020-08-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0011_mynews'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotnews',
            name='lean',
            field=models.FloatField(max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='hotnews',
            name='polar',
            field=models.FloatField(max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='mynews',
            name='lean',
            field=models.FloatField(max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='mynews',
            name='polar',
            field=models.FloatField(max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='searchnews',
            name='lean',
            field=models.FloatField(max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='searchnews',
            name='polar',
            field=models.FloatField(max_length=200000, null=True),
        ),
    ]
