# Generated by Django 3.0.8 on 2020-08-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0012_auto_20200810_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='imgurl',
            field=models.CharField(max_length=200000, null=True),
        ),
    ]
