# Generated by Django 3.0.8 on 2020-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0013_mynews_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20000, null=True)),
                ('setting', models.CharField(max_length=20000, null=True)),
            ],
        ),
    ]
